language: go
go:
  - 1.12
services:
  - docker
install:
  - manifests/local-dind/dind-cluster-v1.12.sh up
  - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"
  - kubectl get nodes
  - docker run -d -p 5000:5000 --name registry registry:2
script:
  - pwd
  - ls
  - make test
  - make docker-push e2e-docker-push
  - kubectl apply -f tests/manifests/e2e/e2e.yaml