language: go
go:
  - 1.12
services:
  - docker
install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - mkdir $HOME/.kubeadm-dind-cluster/ && mv ./kubectl $HOME/.kubeadm-dind-cluster/
  - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"
  - manifests/local-dind/dind-cluster-v1.12.sh up
  - kubectl get nodes
  - docker run -d -p 5000:5000 --name registry registry:2
script:
  - pwd
  - ls
  - make test
  - make docker-push e2e-docker-push
  - kubectl apply -f tests/manifests/e2e/e2e.yaml